
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Find the sum of all the even-valued terms in the sequence which do not
# exceed four million.

# build fibonacci sequence to limit
# luckily it's short:

fib = [1, 2]
while fib[-1] + fib[-2] <= 4000000:
        fib.append(fib[-1] + fib[-2])
print(fib)

even = [n for n in fib if n % 2 == 0]
print(even)
print(sum(even))

